### ISSUE TITLE
can't focus via keyboard

### ISSUE THREAD

**Issue by Haroenv** [JSLancerTeam/react-google-flight-datepicker#1]
I've tried to use the demo with keyboard, but I can't get anything else than the link or the video to focus on the page. Is this something that you  have considered while making the library?

**Comment by davidtran** [comment]
Hi,

The accessibility is our todo list. We are going to research and implement it in this weekend.

**Comment by davidtran** [comment]
@Haroenv Just finish the keyboard support for our component at here: https://github.com/JSLancerTeam/react-google-flight-datepicker/commit/ab7dc7f5008b94441d2bd6c0b2199b93c0c5753d

We will publish this change soon!

**Comment by davidtran** [comment]
Just released the 0.1.5 version
