### ISSUE TITLE
Calendar is not scrolling to the next month automatically to the next when I select the month

### ISSUE THREAD

**Issue by ammshath** [JSLancerTeam/react-google-flight-datepicker#21]
Hi,
I am having a issue with the calendar scrolling. The default calendar is showing two months and I have to go to the third month using the next arrow icon. But I want the calendar to auto scroll to third month  when I select any date in the second month
![image](https://user-images.githubusercontent.com/80663280/111103234-fb5f6b80-8573-11eb-9542-5e4a6ff4f063.png)

according to the above image I need to make the calendar auto scroll to the next month (Oct 2021)..

Thanks.

**Comment by davidtran** [comment]
Hi @ammshath, this is not possible, it will break the UI logic for the calendar so I can't implement this request. You can fork this project and make the change.
