### ISSUE TITLE
When isOpen=true by default it starts with end date

### ISSUE THREAD

**Issue by sanketakulkarniari** [JSLancerTeam/react-google-flight-datepicker#36]
Hi,

We are using this and control and it works very fine..only issue is in our use case we always want to have this control in open model. so we used   isOpen="true". But when we do this by default end date is focused and when user tries to select it selects end date first.

We need start date to be focused...
Can you help us with this?

**Comment by davidtran** [comment]
Hi @sanketakulkarniari we will take a look on this issue, thank you for notifiy us.

**Comment by davidtran** [comment]
hi @sanketakulkarniari we have fixed the issue and published a new version on NPM

**Comment by sanketakulkarniari** [comment]
Thanks a lot, @davidtran , I will check. Really appreciate your help.
