### ISSUE TITLE
Support changing dates programatically

### ISSUE THREAD

**Issue by tdehollain** [JSLancerTeam/react-google-flight-datepicker#5]
Unless I missed something it is not possible to change the dates other than through the UI. That would be needed for instance for preset buttons (e.g. "Last 7 days", "Last month", etc.).

I guess there should be a useEffect on the props startDate and endDate to update fromDate and toDate.

**Comment by davidtran** [comment]
Thanks for your suggestion, I will update it.

**Comment by saniyo** [comment]
I confess the desired feature would become usable.

**Comment by davidtran** [comment]
Hi,
This issue is fixed in version 0.1.17
