### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by FernandoRY** [JSLancerTeam/react-google-flight-datepicker#6]
First of all, thank you for this great component. Secondly, I want to ask if there is an efficient way to use this component, I'm trying to build a dynamic form that will contain multiple instances of this component but the render time of each one is exceeding two seconds. Is there any way to make all the datepickers use the same dialog?

**Comment by davidtran** [comment]
Hi Fernando, 

Thanks for your feedback. I will profile the performance of this component in this weekend.

About the last sentence, you want to have a dropdown to switch between single datepicker and range datepicker like the datepicker on google flight website?

**Comment by FernandoRY** [comment]
Thanks for your response,

In the last sentence, I just wanted to know if multiple instances of the same datepicker type (single datepicker) inside the same component can share the same dialog that opens if I click on one of them? instead of each datepicker having its own dialog. maybe this will reduce the render time?
