### ISSUE TITLE
Setting Start Date and End Date with onChange lead to infinit reRender

### ISSUE THREAD

**Issue by kouloughli-hemza** [JSLancerTeam/react-google-flight-datepicker#9]
Hello ,
First Thank you so much for  the great Job ,
i tried to use the DateRangePicker and set startDate and EndDate from my redux, or even new Date() just for test ,
but it always fires the onChange on component mounting which lead to infinit reRender and Crash of the app,
here what i did : 

```
                <RangeDatePicker
                    startDate={new Date()}
                    endDate={null}
                    onChange={(startDate, endDate) => props.handleDatesChange(startDate, endDate)}
                    minDate={new Date()}
                    maxDate={new Date(2022, 0, 1)}
                    dateFormat="dddd D MMM"
                    monthFormat="MMM YYYY"
                    startDatePlaceholder={<Translate tKey="start_date" />}
                    endDatePlaceholder={<Translate tKey="end_date" />}
                    disabled={false}
                    className="my-own-class-name"
                    startWeekDay="monday"
                />
```

To reproduce the issue use `startDate` and `endDate` from redux store and the `onChange` dispatch an action

**Comment by davidtran** [comment]
Thanks for letting me know, I will check this issue.

**Comment by kouloughli-hemza** [comment]
> Thanks for letting me know, I will check this issue.

I will be waiting for a fix ,
at the time i will try to help find any bug 
thank you

**Comment by kouloughli-hemza** [comment]
is there any update on the issue yet ? i can't find what causing the issue yet

**Comment by kouloughli-hemza** [comment]
To reproduce the issue use `startDate` and `endDate` from redux store and the `onChange` dispatch an action

**Comment by davidtran** [comment]
@kouloughli-hemza  Hi, I have fixed this issue, please check.

**Comment by kouloughli-hemza** [comment]
> @kouloughli-hemza Hi, I have fixed this issue, please check.

it works great now ,
thank you lot
